/*
 * map_interface.c
 *
 *  Created on: 9 de jan de 2019
 *      Author: lua
 */

#include <map_interface.h>

INTERFACE_METHOD_IMPLEMENTATION(false, M_MAP_ADD);
INTERFACE_METHOD_IMPLEMENTATION(false, M_MAP_DELETE_BY_VALUE);
INTERFACE_METHOD_IMPLEMENTATION(false, M_MAP_DELETE_BY_KEY);
INTERFACE_METHOD_IMPLEMENTATION(NULL, M_MAP_GET);
INTERFACE_METHOD_IMPLEMENTATION(NULL, M_MAP_GET_VALUE);
INTERFACE_METHOD_IMPLEMENTATION(NULL, M_MAP_GET_VALUES);
INTERFACE_METHOD_IMPLEMENTATION(NULL, M_MAP_FIND_BY_VALUE);
INTERFACE_METHOD_IMPLEMENTATION(NULL, M_MAP_GET_KEY);
INTERFACE_METHOD_IMPLEMENTATION(NULL, M_MAP_GET_KEYS);
