/*
 * iterator.r
 *
 *  Created on: 7 de jan de 2019
 *      Author: lua
 */

#ifndef OO_BASE_ITERATOR_ITERATOR_R_
#define OO_BASE_ITERATOR_ITERATOR_R_

#include <ooc.r>
#include <iterator.h>

typedef struct IteratorClass_r{
	Class_r _;
	CLASS_DYNAMIC_METHOD(M_ITERATOR_FIRST);
	CLASS_DYNAMIC_METHOD(M_ITERATOR_NEXT);
	CLASS_DYNAMIC_METHOD(M_ITERATOR_IS_DONE);
	CLASS_DYNAMIC_METHOD(M_ITERATOR_CURR_ITEM);
}IteratorClass_r;

SUPER_DYNAMIC_METHOD(M_ITERATOR_FIRST);
SUPER_DYNAMIC_METHOD(M_ITERATOR_NEXT);
SUPER_DYNAMIC_METHOD(M_ITERATOR_IS_DONE);
SUPER_DYNAMIC_METHOD(M_ITERATOR_CURR_ITEM);
#endif /* OO_BASE_ITERATOR_ITERATOR_R_ */
