/*
 * list_interface.c
 *
 *  Created on: 7 de jan de 2019
 *      Author: lua
 */


#include <list_interface.h>


INTERFACE_METHOD_IMPLEMENTATION(false, M_LIST_ADD);
INTERFACE_METHOD_IMPLEMENTATION(false, M_LIST_ADD_ALL);
INTERFACE_METHOD_IMPLEMENTATION(false, M_LIST_ADD_ALL_C);
INTERFACE_METHOD_IMPLEMENTATION(NULL, M_LIST_GET);
INTERFACE_METHOD_IMPLEMENTATION(-1, M_LIST_INDEX_OF);
INTERFACE_METHOD_IMPLEMENTATION(-1, M_LIST_LAST_INDEX_OF);
INTERFACE_METHOD_IMPLEMENTATION(false, M_LIST_REMOVE);
INTERFACE_METHOD_IMPLEMENTATION(false, M_LIST_SET);
INTERFACE_METHOD_IMPLEMENTATION(NULL, M_LIST_SUBLIST);
